### ISSUE TITLE
Dirty windows aren't honored

### ISSUE THREAD

**Issue by bringert** [venice1200/SSD1322_for_Adafruit_GFX#3]
I noticed when rewriting the display() code that the full buffer is always sent, ignoring the dirty window. I've fixed that in my fork,
(https://github.com/bringert/Fast_SSD1322_for_Adafruit_GFX) but it can't be pulled in directly, since my code probably only works with 128x64 displays. They use a weird protocol where each 4-bit nibble is duplicated and sent as one byte per pixel.

**Comment by venice1200** [comment]
What means "dirty window".

I just modified the original library to get it working with the SSD1322 Controller and the 16 "grayscales".

**Comment by bringert** [comment]
The original library uses window_x1, window_x2, window_y1, window_y2 to keep track of which part of the buffer has been modified. This rectangle is called the "dirty window". It then uses SSD1327_SETROW and SSD1327_SETCOLUMN to tell the controller which data it will send and sends only the data from the dirty window.

In your code, you always set the dirty window to the full display, which works, but makes it slower to update the display when only a part of contents have been modified: https://github.com/venice1200/SSD1322_for_Adafruit_GFX/blob/83bd78bd2281471bef946fa8cf8091cc970b7e65/SSD1322_for_Adafruit_GFX.cpp#L315

**Comment by venice1200** [comment]
Understand (now what these variables do).

As my application redraws every time the full screen for scrolling and light morphing, dirty windows are not needed in the moment.

I will close this issue as well and come back to you in the last issue 😄
