### ISSUE TITLE
128x64 pixel displays with duplicated nibbles aren't supported

### ISSUE THREAD

**Issue by bringert** [venice1200/SSD1322_for_Adafruit_GFX#4]
I've forked the library to make it work with 128x64 displays. The code is here: https://github.com/bringert/Fast_SSD1322_for_Adafruit_GFX
but it can't be pulled in directly, since my code probably only works with 128x64 displays. They use a weird protocol where each 4-bit nibble is duplicated, and sent as one byte per pixel.

**Comment by venice1200** [comment]
Hi,
Is your controller also a SSD1322?

**Comment by bringert** [comment]
Yes, it's a NHD-2.7-12864WDY3 (https://www.digikey.se/en/products/detail/newhaven-display-intl/NHD-2-7-12864WDY3/7355952).

It has an SSD1322 controller, 128x64 resolution and 4 bit grayscale.

**Comment by venice1200** [comment]
Nice, looks more like a 4:3 Display.

I will close this issue and answer through the others.
